const FAQs = [
    {q: '연령대가 어떻게 되시나요?', type: '객관식', options:[
        {answer : '10대'},
        {answer : '20대'},
        {answer : '30대'},
        {answer : '40대'},
        {answer : '50대'},
        {answer : '60대 이상'}
    ]},
    {q: '성별을 알려주세요.', type: '객관식', options:[
        {answer: '남'},
        {answer: '여'}
    ]},
    {q: '최종 학력이 어떻게 되시나요?', type: '객관식', options: [
        {answer: '고등학교 졸업 미만'},
        {answer: '고등학교 졸업'},
        {answer: '대학교 중퇴'},
        {answer: '대학교 졸업'},
        {answer: '대학원 졸업'}
    ]},
    {q: '거주 지역을 알려주세요.', type: '드롭다운', options: [
        {answer: '서울'},
        {answer: '부산'},
        {answer: '대구'},
        {answer: '인천'},
        {answer: '광주'},
        {answer: '울산'},
        {answer: '세종'},
        {answer: '경기'},
        {answer: '강원'},
        {answer: '충북'},
        {answer: '충남'},
        {answer: '전북'},
        {answer: '전남'},
        {answer: '경북'},
        {answer: '경남'},
        {answer: '제주'},
    ]},
    {q: '거주 지역을 알려주세요.', type: '드롭다운', options: [
        {answer: '서울'},
        {answer: '부산'},
        {answer: '대구'},
        {answer: '인천'},
        {answer: '광주'},
        {answer: '울산'},
        {answer: '세종'},
        {answer: '경기'},
        {answer: '강원'},
        {answer: '충북'},
        {answer: '충남'},
        {answer: '전북'},
        {answer: '전남'},
        {answer: '경북'},
        {answer: '경남'},
        {answer: '제주'},
    ]},
    {q: '거주 지역을 알려주세요.', type: '드롭다운', options: [
        {answer: '서울'},
        {answer: '부산'},
        {answer: '대구'},
        {answer: '인천'},
        {answer: '광주'},
        {answer: '울산'},
        {answer: '세종'},
        {answer: '경기'},
        {answer: '강원'},
        {answer: '충북'},
        {answer: '충남'},
        {answer: '전북'},
        {answer: '전남'},
        {answer: '경북'},
        {answer: '경남'},
        {answer: '제주'},
    ]},
    {q: '거주 지역을 알려주세요.', type: '드롭다운', options: [
        {answer: '서울'},
        {answer: '부산'},
        {answer: '대구'},
        {answer: '인천'},
        {answer: '광주'},
        {answer: '울산'},
        {answer: '세종'},
        {answer: '경기'},
        {answer: '강원'},
        {answer: '충북'},
        {answer: '충남'},
        {answer: '전북'},
        {answer: '전남'},
        {answer: '경북'},
        {answer: '경남'},
        {answer: '제주'},
    ]},
    {q: '거주 지역을 알려주세요.', type: '드롭다운', options: [
        {answer: '서울'},
        {answer: '부산'},
        {answer: '대구'},
        {answer: '인천'},
        {answer: '광주'},
        {answer: '울산'},
        {answer: '세종'},
        {answer: '경기'},
        {answer: '강원'},
        {answer: '충북'},
        {answer: '충남'},
        {answer: '전북'},
        {answer: '전남'},
        {answer: '경북'},
        {answer: '경남'},
        {answer: '제주'},
    ]},
    {q: '거주 지역을 알려주세요', type: '드롭다운', options: [
        {answer: '서울'},
        {answer: '부산'},
        {answer: '대구'},
        {answer: '인천'},
        {answer: '광주'},
        {answer: '울산'},
        {answer: '세종'},
        {answer: '경기'},
        {answer: '강원'},
        {answer: '충북'},
        {answer: '충남'},
        {answer: '전북'},
        {answer: '전남'},
        {answer: '경북'},
        {answer: '경남'},
        {answer: '제주'},
    ]},
]

export default FAQs